### ISSUE TITLE
What to do next....

### ISSUE THREAD

**Issue by Suleman-Elahi** [opservices/fivemetrics#2]
I don't have an idea about Docker ... I have run the commands you have mentioned on a server on DigitalOcean. But to do after that. How to access the tool.....?
![image](https://user-images.githubusercontent.com/24384996/44031237-f820187a-9f20-11e8-95d4-a91f693fd8a2.png)

**Comment by lockland** [comment]
Hi @Suleman-Elahi,

Can you to inform us about operation system are you using and what docker version are you running?

After you have started the container just open the url: http://localhost:5555 in your browser, if nothing goes wrong, you'll see the fivemetrics login page.

**Comment by Suleman-Elahi** [comment]
Yeah.. I tried opening the local host (201.97.33.21:5555) as 201.97.33.21 was the ip of my droplet. But nothing happened!!!! I was using Ubuntu Xenial on the Droplet and Docker version should be the latest as I ran the full system upgrade before installing it !!!....... I have destroyed the droplet btw so I can't give any further information about the environment !!!!

**Comment by lockland** [comment]
I'll try to reproduce those errors on Ubuntu.

As you are using the DigitalOcean, could you test it using an image with CentOS 7 and give us a feedback? I've used that distro successfully.

**Comment by dirtyren** [comment]
Hey @Suleman-Elahi , did you try the docker on CentOS / RedHat ? Tks.
